### ISSUE TITLE
Finish documentation

### ISSUE THREAD

**Issue by dbcarelli** [lucasfutch/Arduino-Robot#1]
Lucas:
1) user manual + installation
2) video
3) take pics of caster wheel
4) Add in throughput calculations - mention that maximum is actually 30 times per second because camera limitation

Dani:
1) Put graphs and explanation of PID attempt
2) Put pictures of AHRS
3) Add reactivation pics
4) explain why we used reactivision

**Comment by dbcarelli** [comment]
Dani:
-Explain why we used XBee

**Comment by lucasfutch** [comment]
done
